package com.example.quickscanr;

import static androidx.test.espresso.Espresso.onView;
import static androidx.test.espresso.action.ViewActions.click;
import static androidx.test.espresso.action.ViewActions.scrollTo;
import static androidx.test.espresso.matcher.ViewMatchers.hasDescendant;
import static androidx.test.espresso.matcher.ViewMatchers.withId;
import static androidx.test.espresso.matcher.ViewMatchers.withText;
import static androidx.test.platform.app.InstrumentationRegistry.getInstrumentation;

import static org.junit.Assert.assertEquals;

import android.util.Log;
import android.view.View;
import android.widget.TextView;

import androidx.test.core.app.ActivityScenario;



import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;
import androidx.test.core.app.ActivityScenario;
import androidx.test.espresso.contrib.RecyclerViewActions;
import androidx.test.espresso.matcher.ViewMatchers;
import androidx.test.ext.junit.rules.ActivityScenarioRule;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;
import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.uiautomator.UiDevice;
import androidx.test.uiautomator.UiObject;
import androidx.test.uiautomator.UiObjectNotFoundException;
import androidx.test.uiautomator.UiScrollable;
import androidx.test.uiautomator.UiSelector;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;


import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RunWith(AndroidJUnit4.class)
@LargeTest

/**
 * tests admin delete functions
 * referenced https://stackoverflow.com/questions/34439072/espresso-click-on-the-button-of-the-dialog
 *      for allowing permissions to be automatic
 */
public class AdminDeleteTest {
    @Rule
    public ActivityScenarioRule<MainActivity> scenario = new ActivityScenarioRule<MainActivity>(MainActivity.class);

    private static boolean userSet = false;

    FirebaseFirestore db = FirebaseFirestore.getInstance();

    private static String testEventId;
    private static String testImgId;
    private static String testUserId;
    private static String imgUserId;

    private static String testEventName;
    private static String testUserName;



    /**
     * Uses UIAutomator to allow permissions on startup
     */
    private static void allowPermissionsIfNeeded() {
        UiDevice device = UiDevice.getInstance(getInstrumentation());
        // for notifications
        UiObject allowButton = device.findObject(new UiSelector()
                .className("android.widget.Button")
                .textContains("Allow"));

        // for camera perms
        UiObject whileButton = device.findObject(new UiSelector()
                .className("android.widget.Button")
                .textContains("While using the app"));

        // look for While using the app for 1s
        if (whileButton.waitForExists(1000)) {
            try {
                whileButton.click();
            } catch (Exception e) {
                Log.d("PERMS", "Failed to allow camera permissions for testing");
            }
        }

        // look for While using the app for 1s
        if (whileButton.waitForExists(1000)) {
            try {
                whileButton.click();
            } catch (Exception e) {
                Log.d("PERMS", "Failed to allow location permissions for testing");
            }
        }

        // look for Allow for 1s
        if (allowButton.waitForExists(1000)) {
            try {
                allowButton.click();
            } catch (Exception e) {
                Log.d("PERMS", "Failed to allow notification permissions for testing");
            }
        }
    }

    /**
     * set user to admin
     */
    @Before
    public void setUp() {
        // only setup once
        if (!userSet) {
            allowPermissionsIfNeeded();
            try {
                Thread.sleep(5000L);    // let database setup
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            // go to profile
            try {
                onView(withId(R.id.nav_ad_profile_btn)).perform(click());
            } catch (Exception e) {
                try {
                    onView(withId(R.id.nav_o_profile_btn)).perform(click());
                } catch (Exception e1) {
                    try {
                        onView(withId(R.id.nav_a_profile_btn)).perform(click());
                    } catch (Exception e2) {}
                }
            }
            // edit current user type to be admin
            onView(withId(R.id.user_edit_profile)).perform(click());
            onView(withId(R.id.edit_profile_usertype)).perform(click());
            onView(withText(UserType.getString(UserType.ADMIN))).perform(click());
            onView(withId(R.id.save_profile_btn)).perform(click());
            userSet = true;
        }

        try {
            Thread.sleep(3000L);    // give 3 second between tests to be safe
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }


    /**
     * add an event for testing
     */
    @Before
    public void addTestEvent() {
        testImgId = String.format("default_test (%s)", System.currentTimeMillis());
        testEventName = String.format("Test Admin Event(%s)", System.currentTimeMillis());
        // add the test event data to the db
        Map<String, Object> data = new HashMap<>();
        data.put(DatabaseConstants.evNameKey, testEventName);
        data.put(DatabaseConstants.evDescKey, "Event Description");
        data.put(DatabaseConstants.evLocNameKey, "Location");
        data.put(DatabaseConstants.evStartKey, "26-03-2024");
        data.put(DatabaseConstants.evEndKey, "26-03-2024");
        data.put(DatabaseConstants.evRestricKey, "Restrictions");
        data.put(DatabaseConstants.evTimestampKey, System.currentTimeMillis());
        data.put(DatabaseConstants.evPosterKey, testImgId);
        data.put(DatabaseConstants.evAttendeeLimitKey, -1);
        data.put(DatabaseConstants.evOwnerKey, MainActivity.user.getUserId());

        db.collection(DatabaseConstants.eventColName).add(data).addOnCompleteListener(new OnCompleteListener<DocumentReference>() {
            @Override
            public void onComplete(@NonNull Task<DocumentReference> task) {
                if (task.isSuccessful()) {
                    DocumentReference documentReference = task.getResult();
                    if (documentReference != null) {
                        testEventId = documentReference.getId();
                    }
                }
            }
        });

        Map<String, Object> dataImg = new HashMap<>();
        dataImg.put(DatabaseConstants.imgDataKey, "/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAI6AjoDASIAAhEBAxEB/8QAHQABAAICAwEBAAAAAAAAAAAAAAEHBggCBAUDCf/EAEUQAAICAQMDAQUEBwUGBQUBAAABAgMEBQYRBxIhMQgTQVFhFCIycRUjQlJigZEWgqKxsjNDU3KSoSREc4PBJSY0dITR/8QAGwEBAQADAQEBAAAAAAAAAAAAAAECBAUGAwf/xAApEQEAAQMEAgIBAwUAAAAAAAAAAQIDEQQFITESQRNRYSKx4RRxkaHB/9oADAMBAAIRAxEAPwDakAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA87XtY0/RNKydQ1XLqxMOiPdZdbLiMV/wD7z8AO/KXHHBh28OpW1tocw1zWMWrI8cY1b97c/wD24+TXjfnWLdO+9Zlt3p7i52Lj2NxTo8ZV6+Lb/wB1E9jYns3OxLL3xqM5WTl3vDwp/wCu3jmTLgZBqftQbeolJYOiarkQT4jZbKumMv6y5Iwvag2/dNLI0HVa4c8SnVZTb2r58KRYmi9K9l6RCpYO2tMU61xG22lW2fm5S5bZ2dT6b7P1JcZu2tJtfopPFipL8mkXCOO0eqW0d1uMNJ1vFeTL/wAte/c3L+7LyzNoSb55S+nBr3vj2cNDzsW2za91ul5KTcKbZO7Hk/5/ej+cSutB6jb46Ta9HQt3RyMrDT+7DJtdn3PhKufrOJMK3LBjmzdz4G7NJqz9LslKuXHfCTXdBtJ8Ph8Px5TXhoyMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHGxtR8MDq6rqWLpOBkZuoXQoxMeuVt1s3woRS5bZqxu3WNa6tb0p0bSKZ1NfrVVe/uaZS3x76yPxulF+F6wTUUZF7Qu8snUNRx9u6NGWRZXkxqroX/AJzN5XbD6wq5Un8HNwRZ3STYWNsfbyx+/wC06nky9/nZcue661/5RXwQgdnpx0/0TZGmfZtJx39oml9oy7VzdkP+KXy/hXhGaRjwuEIx7fCXBL8cmQE+D596T4bRzQBpNGLb52th7j0t05WNTfbGM1X7yPKfcuJQ59UpLx49PUyk4WdrT5fhL5gardI8rI6e9Unt7IsnPAv7FVK1rvnRZJ9rfH7ULXw/k/eG2EZdxq317VGFv/a19FlULrMzJxH49O5VSX9J2GzGjZP2zTMPJ9XdRCxv6uKMZ7PTugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwuTGeoG4HoG2sjJx5V/brOKcSNnmLtlz2t/wAMUnOXH7MWZK/wsoLrvlZmtazg6Bp9jjZl3R0qlR48WXRUr7WvlClJJp+tjA8r2f8AbENwa3bvfL95bh47nh6R76PErPL97kv+OUnP+cpGxsI8cL4L0PJ2zpGJoeh4OmafX2YeJVCmqL5bUYrw2/Vv48nrmQlo+d3Krlw+DnyJLlAat6b1C3rT1yxdEvyMjLxrcj3OTp/2VVwoi+VJwXHc1D1943xI2fqk3BfH6nxli1KXd2rv9E+Fz+XJje8t/bb2bR3a/q2Pizce6FHLnbNfSC+8MojqPvrTtkaE87O7rr5v3eNi1/7S+z4RRSde5OqW57Xk36vibaxJJ9mNi48bLOH6KXcn/XlHirVs3qV1C/tLlUWU6JgwlTp9Vq+v4183x8SwcePCbS9Eeb3jeatNV8VjGfbvbdtdN2j5b3Sq+ryzM/Q8LPVONiaht3IcMuulNV2QvnGdWZHubl2ysj2yTbakbQdLtbxNc2TpGTh2KTjjVwur5XdVZ2ruhJfBoqTfWBiae9K1HOg56bOEsTUWvPGJkQcZt/wxm6rOfVdph3QfdFWw985+3tz6jVix7Ps9ltlqdM7Ite7lGXok4+jZ1dBqZ1NmK6u/bl6qzFq5MU9em3SZx74lc7z6y7P2pRJZOqV5uYo8rEwGrrH48c8PiP8ANmv+9faS3Hq05UbWxa9IxnLtjZ4vyJ/JctdsfySkbrWbd6lquBpWNLI1PMx8OiK5dmRbGuKX5tnm6FvLbev3WU6Hrum6hdBcyrxsmFkkvyTNNND6Zb96hZcdR1my6qqb5eXq1knJpvz2Ql97/tFGWal0A1zQdPytZ0fcVeRmYFE8mmNWLOFrnFc9sH3vhnx+e35eGeVxOMtvITU/wnIpboJ1Nu3Vi0aZq6bz/svv6bv+KotKyP5xcotP4xkXRF8rk+yJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8MzJqxcW6+6XFdUJWTfySXL/AMigtjYdu4uteXm5vNq0LD95JWRTUcvLbsfbJLj7lbUOflAt3qBav7O347k4xypRonJPj9W/Nvn/ANOMzBPZ4rln7Y1Dc+TGay9wahfmyUkvu1qThXFcfDiJlSkrbqXEUjkIhBTjhh+jCREmkm2B4u8dRnpO3NQzaU3bVTKUEly+7jxwvizWXZ22MLPxq9f1rjVNXz4xybcjIl7zlyXPC+Ho+DOvaB6v6bt/Et0DS3DN1mTXvlFqVeNx5Sk/jL+E1N0jdGs6TT7nTtSzMap8fcha1H8+H4Roa/TXdRa8LVXjLb0N+3YuedynLbKuqFcUoRjGKXCS4SR2K3x6GseB1N3Tg3ffz3kxXrXlVxmv8kyytn9V8LVMmvF1iiOn3z8V3KblVL8+fMTyOr2HVUR5xPl/Z6Wxu1i7+meF04sqdU0/9GZfa7PMaHL8Motea3/kvmvBrD1a6fZO1tRllYNdj0u2fZHn1ok/93L6fJmwtdndx58Nf1+RleJg4e7tIuwtYojkcR7J8+tsP8+5H12jW10XYtz3+/8ALU3LS000zV6/b+GtfTPodqG7dJxNX1HUatP0y/79UYV+8ssjy13dv4Yrx6s2L2N0w21s6EZ6Vg+8zO3tlmZL97c/yfHEV9IpHldM6/7K6rqu0r5Qhi4//jMBSfavdSk1ZCLfiXD4m/l7457z607R23GyqrOWrZkfu/Z9PasSfo+6fPbE7Oqq1V25Nujr8OFT4UxmVlQhGPjwebuDd23NsYN9mvavhYi7XzVZaveS8Pwofib4Xokau6r1V6idRMp4G0sLIw8ez7kqdNUp2pcek7mvu/4T2toezfr+p5P23duoVaerHzOEJfaMiXPrzJ+E/wA3I++k2+bVXnXPLGu55RiHqeyZXVqe8N06pXROOPVF/ZlKPipXWyk4f9MYeDaWHKiufUx7Y2z9J2Vo607RKXXS5d9k5vunZJ/tSf8A8fAyI6z4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKe9pHV3pWx9SsTlzHEtiu2XD77XGiP8A2ssZlvSfT56Z0623h3RUbatPojYl8Jdi5Ku9pVrVM7RduxlH3usariYkoccydMOZSkvonci+cSuNVUYQSUIrtil8EvCX9EWB9wAUCpvaM35fsnZL/RlvutV1Cbx8efjmuPa3OxfkvC+rLXnJRX3ml+ZqL7YVqydwaYlZ3TrhZUoKXiK7a5Px83KQGu9l08m2U7Ztt8ybk23z8fPxf5/E7umZccG+q+qmF1lUlYnauYcxafmPxXKXh+GvDPb2N073HvG/jRsCU6FLtlk2Pspi/k5/H8kmbR9OfZ52/okqsvXf/rOWlz7u2Pbjxf8A6f7X95sYka1bZ0LJ3hv/AEmG5L78SrXMqU5Zcqu33nPLbh3LtfL4iuOYrlG2+F0n2Zj6DZpa0HGlRcuLLbPvXzfLfd71/eT8/D0Pe6o4GDDZeRblwnGrHcIwVEuyaUpRgo1/uy5acePSai0UNP2g9bwrrdGWgYudq+NdPFd8bp/r5xk493uow55fHPCZoayzeuY+KcM6Kojt6Ou7V17pip5WnZU9c2vHulPHvfbk4sUu59rb4lwuTIdobywL8eGp6XqNDx1H9Z32KDh4/ajzzFmE6toXWHqNg2PU9Orow1D3lGNZKGNBT/fUeW5Ph/tMry3ol1BxLZVWbay7OPjS6rYv+fcad3aIv4uVT41x7hvWdxrt0zbn9VP5e9143TjbjujkWV/rHKEcVd8nH3UFPvu7G+F7xy4j45ar7iwejXs/YN2kYmsb2jddbfFWV6d3OEK4+q7+PLf8J0+jnQzV57gq13fVM6q6Jq2vFvmrLLpr8Ls4bUUuDamEVFJR4SXwR16afGmKWhVOZy6WkaVgaVhQxdNwsbExoeI1UVqEV/JHe7Vz6EgyYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEnxwl8STo63mw07SszNtlGNeNTO6UpPhJRi2BSu44x1r2jtr4nvu+Gk4eVqTh8u+XYl/2iXfWuIoo3pfRZqXWjeGo5UoWvTsXF0qqaX8ClYv8AqRekVwkZR0jlz4OrnZtGFjzvyrq6aYrmU7JKMUvi22+Ds/AqnrriLJ0/R1qkLLNrQz656zGKfilJ9kpceexWcOTQJeHufqvq+4rLdN6U6XbqlqfZbq1kO3Fof8DfibPJ2t0KnqWbXq3ULUrtY1BtSlQpfqufXhy9ZlsbUy9vT0vHhoGTpk8KEUqo4dkHXGPySXoju6xu/bmhQUtY1rTcNP0V+RGLf5LnkyxEI72jaJhaViVY2DjVY+PUuIQrgoxivkl8D1ZSjWm20kihN4+0ntzTYOvb+NkatkNeJyTx6f8Aqku6X91GET3B1Y6pQsx6tB93ot3j3UoSx8aS9V7yc332R/hXCMZnLJkvXjqfp2RjrTtOtV+n0X+9nOD8ZmRU+YVQf/DhNKU5+i4UTs+zT03vwsa7dO5cSL1HPbso9/H9YottubX7Pd6nd6c9BI4Op4+tb6zVrGo1Je6xYxSoq48rlftcP0S4iX3XHtjxwkYiI1rhf/BPZE5ADj2I5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb4XnwOQAHP1CfIAAAABz9QAPjk5FWPS7bra66l6znJRiv5tmD6n1f2Fpcpxy91aY5xfDjTY7mn/cTAz4Ffab1k6fah/sd2abD/wDYk6P9aRmmmapgalWp6fnY2VF+U6bYz/yYHdPA3w5Pb9lMIxk8i+jHcZLlOM7oRkv+ls97uXzRjG/8yvE0vGtnbCuEMiN0pSfCUa4ysk/yShyBX3s94srMXdOsWPmWqa7l3p/KMZuPBcUfTgrX2fcCzB6WaCr+fe30vKm5eG3ZN2c/4izEZykHB87ao2Ramk4tcNPymvifQEVXu4ekezdZu+05GhYFeWpe8V1dXbzJfvRXia+aZqjuTZ2j5fWn+zeiRlg4fv6qbnB+87LJNKz3fPnjmaST8I3o1Cbrw7ZxXMoxbS5454TNP+k+DDI9oluu2VsXkyy5uxeZOUHY/wCk5iek9tldp9L9pbX7Hpmj43v4x4d9sFOyXHxcn5M1jX2xSXCS8cJHNAxUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9AMQ6hb80jZWlrJ1SV07ZxnOnGpj3WWqK+8/XiMVyuZSaS5RQ9/tIbi1PJshtnaNVsIPzy7ciaX8SrjwmZJ1G0ajfXU3R9uWT/APBXu7MznFdtjxseSrhUn+67HY/5l3aNo+BpGBVh6Zh0YmLWuIVUQUIpfDwi4GvuD7Rmr6b2R3jsvJxqpf72n3lL/lG2KX+ItrYvVTaO8e2vSdWrhlySf2TK/U3fyjLxL+6Zhk4dGTTOrIqhbXJcOFiUk1+T8FUb96E7W3LGd2BjrRNQa5jdhQUYd3L4lKv8Lfn1XEhgXF3r6kuSRrRXtrrNsKXbt3Wadw6en4ov4lJf3bH3f0sO5jb3655M448dn6ZVZKSXvbcfthH6v9exgbDX5NOPVO2+ca64R7pSm+FFfNsp/e3WDExqXi7Lqq1bVL24482pOu2XyqivvXPzzzHiC+M0ebLp/vfdyi9+a7R7r9rEx61KmD58OMOFFv6zUix9obE0Ta6nZp2JH7XYuLcq3791nyUpvzx9PRF8UyotdKN+9Qs+OXv7WXiY3PcqFJWSX8Mao/q4fm+5mZ6f7OezKMWFWV+k8mcfDsllShz/AHY+EXYoxj4SSJ7UXgUxZ7O+x3XKNdOpQfzWdNmK6j7NdOJasja+487T8iL5g5wXj6d0O2RsjwiGmxwuFI6bs3q1hU+7h1Cx74qPalfgRnwv+b1PQ0npluDVJt9Qd2X61j+ksWihURuj4+5ZL17OV5jFR5/a5Ld4XJyJOEfHHoroqjCqEYQgkoxiuEkvCSXw8H2ACgAA+GbHvxpxa5Uk018/HoaZdEcuzF9oCNWRY7LLM2zGcpJp+K7f8uzg3RtjzBo0u3ph2bC9oHJzYRdcLMiOpYyT8WpyUpx/qrEJ6T23ZQOnpWfVqWFRmYs42Y19cba5L4xa5R3DFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMClunVEZ9Ucy9+Z17ewly/P47rpMuVFM9MH2b8zJTmm5aasNqXh9+NmZFdi4+nci5omXUQntJByIZFcJRT+BCrS+BzBRCil6eCQAA+YaHwAgAP0AMEcgCQ2CABPJAQElU9eOmcd+aHCeFKNWs4fdLGm/CsTXmuT+paxDSaaZRqP0Y6s52x82e1N5RtqxqrOyM8jlTxpfGEv4fqbaYGZRl4dN9N0bK7I8xkvRoqrrT0j0/feE8zG7MPXqY9teVx922P7li+Mfk/VFL9HepGpdONy2bT3eprTq7vs8nN8vEl8Gn8azGYG44PnTdC6uFlUozhNd0ZRfKa+DPoQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP0AflAUrm1PQusU7K2l9oujlfrnxH3GRCNNqh9Y3UY8n8laXHTJSgmviVz1s0lT0OnXexyq01WQzY18qcsGyPbdw15ThxC1fHmo9LpfuKer6HPFzrIT1XTJ/ZcvsXCnJJOFsV+7ODjNceifBlE5jCT2zkhhEkVxABQAAAhsAAAyAAIJAAAAAAJQCAESj3Lhmv3tM9Ov0lpv9q9Fq41bTo83xhDl3Up+v1cTYM6+bRDJosqtip1zi4yi/Kafhr+jECkvZk3v+lNK/QOZkKcq6vtGFzJcqtNKyn69jaa/hmi+U+TRzM970i64xqrnZXpWNnxyK4t8RljWrtf8ASLkv7hu9jzjOClW04ySaafqn6MxxgfUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHyuhG2qUJpSjP7rT9Gn8DXe6jN6Wb7tvrc7NF92pKvt/HpsH58/v487f51M2NMV6h6FZreit4VVc9Tw39qw/eJdrsSacG+HxGcHKuX0mB7+JfDIphZXJShNcxafKa48Pk7CKe6Iblg3kbWn733OBVDI02y1cSnhyclCElzyp1NOqXPnmsuBPkylISyABCjAABkAAGQSQwDIRKAAAABx4AALwSiCQJQCJXqBq37Yu31xoWvVx8czwb+F68rugXR0I197k6V6Bm2ScsiFCxrm/Vzr+6/8jHPahwJZvSTVLaod08SynJ/JRsXcY97G2e7di6tp85f/iZ3dBfScExP2kNgwQvREmKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcZw7nzzwcgBQO+qHszf0NZx6O3Hxrf0jFd3bF42RNVZkOEvChY6b+5/8Rl64tnvK00+U16mD9XtIhqGiY99kZPGqtePlxj47sXIi6bfPwUXONnjz+rPp0e1fJ1XZWEtTl3alhueBmctNu6mTrk/5uPJY6JZyACgPiS/QgCGwAAIZIYEAlogAAAAAAEogmIEoBADC+s+M8vpfummC5lLTr2l82oNoo32LcjnUd1VJtQnTjWpfXusRsH1FcVsjXe5pQ+w38t+iXYzXL2LV/8AcG4n8PsOP/rkPUI20j6IEL0JMVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeZufTI6ztzVNNm2lmYtlHKfDXdFrnn+ZVfSDU3Hdm4sKfEY50KNVrh+7Jx9xdH81ZQy5bHxFlB5UVtbqrB8RhRVqEkmnwo42oJyUn/AP1UyX0U0WntJ6XyvgSfOiSlBNP1R9Cqn4EcAAQCWQAHoAwOJIAAAAAAAJIRLAlAICRhHWy73HSrdc0+H+jbkvzcGimfYwwpwluvN8e6/wDD40P5d8n/AKjOPan1qGn9LcvDU37/AFG6vFgl/wA3dL/DFnD2S9DnpvTB513cp6nl2XrnxzCP6uL/AKRE9IuuPlIkAxUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABElzF8FU9dNBjl6di6lLmuld2BmWR5bqpta7Lkv3qrlVPu+C7y1zpaxg4+pafkYWdTG7EyK5U3VzXKnCS4af8AIDF+mW4v7RbVxcq/thmV91GXUpd3ur4Ptsjz8V3L1MxRrPsvW7emvVbI2vrMZV4Wa663kTl3K2zyqcjnj1tglCSXpOs2Tps74pryvmZzzyxj6fUnkgEZDIJDAgBhARx9A/BIAgEjgCATwQwJQI5JQEoiUkl5ZJXnWnftOxNoX5nKln3804dX71rXq/pH1YiMihvaM1u/enUrTNoaI+/7JdGh9vL5yLeE/RekIm1u3NKo0PQsHSsOPbjYdEKK1/DFcGs3spbKv1TW8vfGsp2OErK8Sdi82Xyb97b/AC5cTaqMe348kmUjhyABFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxz6gAU97RPTx7w2y8/TKe/W9Li7KFHw7q/WdXPz8d0f4j5ezx1C/tdthYmfd3avp6jXfJ+HdDj7lv8y5X8TVXqlpOV0l6pYW89Epl+hdQtf2mqvxGM5f7Sr8pcd8f4jKmfUpLadNNcoHl7f1XG1jS8XOwbY3Y2RVG2qcWmpRaTTPUTExiVjkAAEAPyAAAAAAACeB6gQESkOAPhmXQx6JW2TUIQXdJt8JJLy+TTzVHm9eOr/wBkxLbKtCxE4xuS/wBjjxku6z5d1kvQsv2sN5PSdqU6BiWduRqjfvuOfu48eO7+r4RkXs07I/sxsGnPyquzU9YSyr3KPEoQ4/Vw9OfCfP8AMTwkcrO0HSsTQ9LxNN02iNGFi1qqqtL0iv8AN/Hk9MLwgYqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD9GeFu/bmn7n27maRq1fvMTJh2P5wlz92cfk4vyme6ANZukev5vTbd1/Tvdt3EHZ36dlSTjXOMue1R+UZtNr5S5ibI1WKyKcWYF1m6cYnULQXSlCjV8ZOWFlP9mXxhL49rKr6SdXcrRtSs2h1F78TUMOf2evLvfq16Qtfz+Kn6SRnE+XE9sZ45bKoHVx8qu+uM65KUZLlOL5TXz5Pv3R455XBJ4XOXP0DfB5Ova/p2hafZm6rl04uNWuZWWyUUkUFuj2i1k5ywdj6Nk6ldN8QtthOPd9VXFOcixHuUmr6bIOSHcvmavYu7uueoVLJo23OFMvKi9PUf8AtOxSGT1X6p7Z/Wbm2h3Y3q5/Z7K0l9ZRc0hin7Mz9Nov5hs1Wh7Ut/ufO2afefTUFx/p5GN7Qe7tbUloGz1c18avfZP+iBcR9mZ+m1KkiUa16X1i31pd2Nk702VlY2kWzjCeRVTZCUHJ+OIteXz8C+Nvbk0vXcVX6ZnUZMPR+7mm4v4xa9U+Vxw/KZMfS5+3ukWNKD5OLugly34RUvVfqxpO1sOdFF/2nJt5ilU/5NR+b+vpEkRMkypTqhgf2y9obSdLnP3kcv7LXZB+ldfMrHD/AKDcjHhGuqMILiEUoxXySNUvZ729rO8OpNu/9VodOBTZbZXPjiNt0ouuMIfvQhDx3G2EFwuDGeVhIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANclP+0D0803dG1czVI49VesYEFaspR4k6Y+bIP95dnJcBj3UH3f8AYLcrs/D+jcnuab5491L5eSDSvamq7629uiW0cHcGRpk6rZVyTaurgox55jGSfjjhpIubT7OpGVPGxpb1xpNziuXp8YuaT+8pS/Z+TaRVuvr33tE5jr5SruXd/LHhFl04qUku/jtfh/TwcDdt0vaS9TTRVxPbtbft9rUWaq6o59KU9oTWMi7V9Fo7siqnJ02vPuqnkSucZycl2qcvWKUOUbOdEdjaZtHZOnyxKqp6jmY8LsvM7F7y2Ul3cd3r2rnhI1O6tUX2U7ay7pSlmYVEtHvi/K78ax9jb/jrsUjan2cdaWr9JNFjOUfe4ClgT8/8NtR/wdrO/FXnTFWXGqjxmYWa4J/Ej3a44fp8jmCo823QtLtl3W6dhTn+9LHg3/kdynHrorUKYQrgvSMI9qX8kfYAYR1lxff9MdztJytpwbMinx+G2td8JL6qUUzVHceIsn2hNYxacjJxYW5c5WTxLZUyb93GUl3RfKXcbedRpue3vscVKUs3Jx8X7q54jK2Pe39FHub+hqDtDJW4es+uaup++rtvyciE1xx2ys4h/LtRr6u5NqxXXE4mIbGltxcvU0THcrQwNp5eJKWr065rGbjYSU7cDUsmWVj5KbSdfbJ/jafh/BpMrTOwa92e0fLS8mELMJavHE9xFJ1qmry60vRR4rkuC/cyE1s3T6qOHdkazhrj5pZdXd/hizX/AKbapTL2iIajfZGFM9ayLHOT4/G8hJ/1mjW2u5cuaeKrlWZl9NfRRRemKIxDd7ExqsWqFdEI11QiowhGKUYr5JfBH3IUk14aHcuOeUdFppAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwbqdrGJp+hToy7FCqzm/Ifq44tLVl0uPV8pKHj9qxGWatn06ZhZGbmXQoxMeuVt1s/EYQim3Jv8kae9cN6Z2sZEtMqVsdQ1dU3XYs2m8bG9cfFcf2Zvn31n1cIttIk8cysRniHg9L4Xa/vfU9fya3B2WWWSXnhTsk5uP8k0i9sb8LMO2DoMND0ajHS5nx3Tk/WUn6szGpqKl49Vwfn29amNTfmY6jh7bQaebGnime55VJ14w7cPBVsJSWFn2Rv54b7MuuHZ/jqfHnx+rMb6W9SszYW4a83D7sjR82MftmDFriX73b54VkfVfNPgvjWdJw9f0fJ0rU4yeLkL8UX96El6SXPxT8mq+7tB1Damr36XqFb7FLurmk+y2Pwsj8GmvD+Xoel2LXRqLEWqp/VS87uekm1cmuOpforoOs4Ou6Vh6jpV6yMPKrVlVkfRxa/z+B6Jph7NnU/+zWrR0PWb5PR8+1KuUvMcS+XpL6Rn8TcuqTlz3Hdcp9CG+FyScbHxECpeue446XpmXZS08jTMGzLg0+XXkXqWNjenz77n58fdKB6D6W6sLN1GS5V0/dVzfxjFcGZ+1Jmzjh65iO1Qt+36da0k13YzpuUfz4tjJnz6YYzp2Zp0VX2SjDtsjx5Ul+Lk5G911U6aYpjt1tmopq1GZ9O/1LjrGVsyNOhSvWZjZdeXB0Pixdvq4/N/Hg1dy6svEzLHke9rye5ykrE4ybfxakuX6v1Xk3Fi04pN+EfPNxMbPolTnY1GVTLw4XVqaf8AVHntt3z+ko+K5TmPt1tdtUaiv5KZxLXPbfWHe+3MeONh61lfZo+I13cXdi+nemWHtv2nNw4+TGOtYWnahjvw+2LxrF9eeZI9bW+le19S5dGPfptzf/lZfdb+sJcorXc3RzVtPrsu0i+vU6YfsQTru4/5X+Lx8mel0+8aW/xFWJ/Lh3ttv2eZjMfht5sHqntzenu6cC6zG1Fw7/sWUu2xr5wfPbNfWLZnkJqfPC9D81Nt6jl6ZqmPV3T7IWpqDm4Ouaf4oS9YT58crjz4Zv70o3FPc+zMPPvl35C5qtnxx3yj47uPr6nTc/DMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS9AKt6y67Viwrxcnunp2HjWavqVafHvqqmvdUN/D3lrXh+JRrmjWjpxgZm6N06juXWZu26V05ubT+9bJ8ycfovwr5LwWn7T2VVgy3HXk2QrlqOn6XXRFvzaqsq+ViS/h7q2zwemFmFi7AwciVlePRXV3XTskoxjJfi5fw8vk5e7367WnxRHM8OltVqi5fibnUcs0qj2xSS4SOxX54MFp6n7WszVjfbbYJvhXTplGt/Jt/BfUzamyMownCSlCa5jKL5TXwfPyPD6nR37UeVynGXrbeot3s/HVl38Wt3WwqjwpTfau58Ln4HndR9iR17QpYWqVRhelzi5S+86J//MX6NHo4WRGm2E5Vubi+Vw+PJlGDr2Jm84eoQcK7OUnNeOTc2zwiPPyxX6/loa3znjxzT7aL42k2424LdJzezHyIznRxa+I965+438FL0T+bTN0/Zx3pLdGx1iZ11lup6TNYtsrOe+cO3mucufPd2+H9UypevXT3Hqyc/VoWKFrwpZFc+5JOVDi2vq5Qnx+dZ2fYzcp6vuZzk21i465/92093YuTctxVVHLyd2mKapiOm1afK5QIj5SJPq+al/aM6X2b40iGoaJCP6dwo8KvwvtNXl+75/eT8xbNTdB3NruydWtr4uqlCShkYmSpLnjxxKPrGXC45P0YcU3zyYB1Q6Vbf3/iSln0/ZtUjDtqz6ElZH6S/fj9GY10RXHjVGYZUV1UT5UzypzZm89L3Tjp4s/c5kVzZi2Ndy+bX70fqjKozXg1y6gdONzdNtRhflQl9lU28fUcXu91zz4+96wl/CzJti9V+XDB3S+J+kcxLj/rXH+JHlNy2Hu5p/8AD0uh3iKsUX+/tdsJ8x9W/pxyZRZh4Wh7Xu1vPod8qaZ3yh6+IpvtivmzCKtUxqcL9IrKrjhwh737QpcwUUvxc+hh2Z16wlVnaXfpd+RTdCVD+3KMa1yuFKcPxdvnnj1aNTZtLVcuTNdGcf6Z7peimmIpqx/1gXXzUq87dGPpVePCGRgxseXKCiozyLZK2zt/hiuF5Nt+iW2rNp9N9H03JkpZTq9/c4vwpT88L6JNI0rjh1b16pRxdt4tqpz8qNNam3KcodqhOyT+L4UrGfoRi1RpphXB/dhFQX5JcHt+nlpfYBAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACpfaH6c27921VPTK1LWNOcrMdeF72MlxKvn6+Gab2bR3fTZLSno+tKfvOHjfZruO7n5cdr/ADP0iOPa/n/3JMZWJw/N7cewd2bXxYZmt6Nn4OPKSSusgu3l/DlN8GW9PuqD0XTqtL1rHtuxaPu1WU8e8rj+603xJG9Gpabi6ng34eoUVZOJfB1202xUoTi/VNfEpHcPsybY1DLlfpWoZ+lRl/uI9t1cfy7lyv6nxv2Leoom3cjMPtY1FdirzonlSe9epU9X0i2OjZdun093ZCNc19pvl83x+Cv8ny2Yht3qFuLQ8lTll35mPJ82U5cpWRkv+Z/ej+aZs7tz2ZdrabmQv1POz9VhDysefbVXL/mUVy/6mWax0O2DqdSh+gacKUfSzClKmX/Znzt6Kxbt/FFEYZV6y9VX5zVyoPXOtuJr2yNQ027Ctqynh24tCk1Z3Suj2SfPwjGPz8ttFmeyHti7S9najrOVS65apdBUdy8umC8S/Jycmj1dF9nDZGm5ryblqOoRUu6NOXenWvo1FLkuPFohjUxqphCFUEowhBcKKXokjYooiinxpfCqqap8pfZegAM2IAAOrqOFj6hiW4ubj1ZONdFwsqtgpRnFrymmaydV/ZvlKVup7B/5paZdPjj/ANKb/wBMjaUPymMD86ltjfOlZC096Prlc67VKOP9ltnDv55TUeHB+fJc/TP2es3WJWax1Dsy8ey2fdHDhYvey+crJr8P5RNq+1/PwTFdq4RIjHSzVM9sM2F022xsiyyzQtN93lWLtnkXTlba18u6Xw+iM1SS9EAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//2Q==");
        db.collection("images").document(testImgId).set(dataImg);

        try {
            Thread.sleep(5000L);    // give 5 second between tests to be safe
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * add a user for testing
     */
    @Before
    public void addTestUser(){
        imgUserId = String.format("default_user_test (%s)", System.currentTimeMillis());
        testUserName = String.format("Test Person (%s)", System.currentTimeMillis());
        Map<String, Object> dataUser = new HashMap<>();
        dataUser.put(DatabaseConstants.userFullNameKey, testUserName);
        dataUser.put(DatabaseConstants.userHomePageKey, "www.g.com");
        dataUser.put(DatabaseConstants.userImageKey, imgUserId);
        dataUser.put(DatabaseConstants.userGeoLocKey, true);
        dataUser.put(DatabaseConstants.userTypeKey, UserType.ATTENDEE);
        dataUser.put(DatabaseConstants.userEmailKey, "test@email.com");
        dataUser.put(DatabaseConstants.userPhoneKey, "1-800-test");
        dataUser.put(DatabaseConstants.userCheckedEventsKey, new ArrayList<String>());
        dataUser.put(DatabaseConstants.userSignedUpEventsKey, new ArrayList<String>());
        dataUser.put(DatabaseConstants.userFcmToken, MainActivity.user.getFcmToken());

        db.collection(DatabaseConstants.usersColName).add(dataUser).addOnCompleteListener(new OnCompleteListener<DocumentReference>() {
            @Override
            public void onComplete(@NonNull Task<DocumentReference> task) {
                if (task.isSuccessful()) {
                    DocumentReference documentReference = task.getResult();
                    if (documentReference != null) {
                        testUserId = documentReference.getId();

                        Map<String, Object> dataImgUser = new HashMap<>();
                        dataImgUser.put(DatabaseConstants.imgDataKey, "/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAJlAlcDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD0iiiivPOMKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACnIjSOERSzE4AFNrR0QA6kvsppxV3YaV3YaNGviP9UP++hTZNJvY1LGHIH90g11VFdPsIm/skcRRWrrdmIZxOgwknX2asquaUeV2Zi1Z2Cr0Wk3k0YcRgKwyNzAVRrsrb/j1i/3B/KtKUFJ6lQipbnLXNhcWihpUwpOAQc81Wrotf8A+PFP+uo/ka52pqRUZWQpqzsFFFFQQFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVo6J/wAhFf8AdNZ1aOif8hFf901UPiRUfiR01NR1fO09CQfrTqyra58vWbm3Y/LIcr9cV2OVrHS3Yv3dut1bPC3ccH0PauQdGjdkYYZTgiu1rB1202yLcoOG4f69jWVaN1czqRurmNXZW3/HrF/uD+VcbXZW3/HrF/uD+VTQ3YqXUz9f/wCPFP8ArqP5Gudrotf/AOPFP+uo/ka52prfETU+IKVVZ2CqpYnoAM1PZ2j3k4jTgdWb0FdRbWkNpHtiQA92PU0oU3IUYORzaaVeuMiBh/vED+dD6VeoMmBj/ukH+VdQ8scQzI6oP9o4pUkSQZR1YeqnNa+xj3NPZI4tlZGKspVh1BGKSuvurOG7j2yrz2YdRXLXVs9pcNE/UdD6j1rKdNxM5QcRscEsxIijd8ddq5qRrG6UZNvLj/dNanh+UYmh78MP5f4Vt1cKSlG9yo001c4iirWpQ+RqEyY4Lbh9DzVWsWrOxm1ZkkUE02fKid8ddq5xT3s7mNSzwSBR1JU4FdFpMXladHxy/wAx/H/62KvEAgg8g1vGimr3NVSujiKKkuIjBcSRH+FiKjrnMiWK3mmGYonceqqTSyWlxEpZ4JFUdSVOK6jT4vIsIUxztyfqeaZqkoi06Y92G0fjxW/sVy3bNfZq1zlKKKKwMQooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigArR0T/kIr/ums6tHRP+Qiv+6aqHxIqPxI6auW1N2j1aV1OGVgQfwFdTXK6t/wAhOf6j+Qror/CbVdjo7S4W6tklXuOR6HvT54VuIHif7rDH0rB0S78m4MDH5JOns1dFVwlzRKi+ZHFzRNDM8TjDKcGuvtv+PWL/AHB/KsjXrXlbpR/sv/Q1r23/AB6w/wC4v8qinHlk0RBWbRn6/wD8eKf9dR/I1ztdFr//AB4p/wBdR/I1ztZVviIqfEdNo1uIbEOR80vzH6dv8+9W7qcW1rJMRnaOB6ntToF2QRoOiqB+lNubZLuAxSFgpIPymulK0bI2SsrI5GWaSeQySMWY9zT7a5ktZlkjJBHUeo9K3f7BtP70v/fQ/wAKP7BtP70v/fQ/wrn9lO9zL2ctzSRxJGrr0YAisnX4QYYpgOVbafoa1YoxFEka52ooUZ9qpa0P+Ja/+8P51vNXg7msvhMXSpvJ1GIk8Mdh/H/6+K6quJBKkEHBHIrsreUT28co/iUGs6D0aIpPoYviCHEsUw7gqfw//XWRGhkkVF6sQBXTaxD5unOQOUIYf5+lYukRebqMfomWP+frioqR9/1JnH3jp0UIiovRRgU6kZgqljwAMmoLK4+1WiS9z1+tdN+ht5GHrkPl33mAcSKD+I4/wqjaxefdRRf3mAP0rd16HfaJKBzG36H/ACKo6FFvvjIekak/ieP8a5pR/eWMZR9+x0dYniCbiKAH/bP8h/WtuuU1Sbz9QlYHhTtH4VrWdo2LqOyKdFFFchzhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABWjon/IRX/dNZ1aOif8hFf901UPiRUfiR01crq3/ITn+o/kK6quV1b/kJz/UfyFdFf4TarsUwSpBBwRyDXW2F0Lu0ST+Low965GtHR7v7Pd+Wx/dy8H2PasqUuWRnTlZnRTwrcQPE/RhiiBDHbxI33lQA/lUlFdVtbnRYytf/AOPFP+uo/ka52ui1/wD48U/66j+Rrna5a3xHPU+I7SJt0KMO6g1Df3L2lo0yKGII4NR6VOJ9Pj5+ZBsP4f8A1qs3EK3Fu8TdGGPpXTe8dDbdaGH/AMJBP/zxj/Wj/hIJ/wDnjH+tULmzntHKyIcdmHQ1XrldSa3ZhzyRr/8ACQT/APPGP9arXmqTXsYjZVVAc4XvUMNjdTn93C5HqRgfmaLuzls3VJduWGRg5ocpta7A3JrUr10ehTeZZGMnmNsfgef8a5ytPQ5vLvjGTxIuPxHP+NFJ2kFN2kdFIgkjZG6MCDWRoVuY2uHYchvL/Lr/AErZpkcax7toxuYsfqa6nG7TN2rtMrapL5OnSnPLDaPxqloE2YpYSfuncPx//VSeIJfkhhHclj/If1qjo83laigJ4cFT/T9axlL94iHL3zoruHz7SWLuynH17VQ0GHZaPIRy7foP8mtWmRRLDGEQYUZwPxzWzj71y7a3G3MwgtpJf7qkj61xpJJyetdFrs2yzWIHmRv0H+RXO1z1neVjKq9bBRRRWJkFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFaOif8hFf901nUqsyMGVirDoQcGnF2dxp2dztq5XVv+QnP9R/IVF9uu8Y+0y/99moCSxJJJJ6k1rUqKSsXOfMrCUUUViZnU6Zei7tgGb96gww9fer1cSrMjBlYqR3BxU/267/AOfmb/vs10RrWWpsqumps6+6i0jTPzF8gewB/wAa56nPI8jbpHZm9WOTTaynLmdzOUuZ3Lmn3zWM27BaNuGX+tdNBcRXMe+Jww/UfWuNpyO8bbkZlb1BwaqFVx0KjNx0O1pAqg5CgfhXKpqt6gwJyfqAacdXviP9fj6KP8K19vE09qjqa5zXJ45blFjYNsXBIPeqEt1PNxJM7D0LcVFWc6vMrIiVS6sFSQSmGeOUdUYGo6KxMztlYMoYHIIyDS1x0d3cRLtjnkVR2DHFON9dsMG5lx/vGun267G3tUT6xN5uouAchAFH+frmqSOY5FdeqkEU3qaK527u5i3d3O1jcSxrIvRgCKdXGx3VxEu2OaRR6Bjinm+uyMG5l/76NdHt12Nvaota3N5t/sB4jXb+PU1m0EknJOSaK55O7uYt3dwooopCCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACpra2lu5fLiGWxk5OMCoa1dA/wCP9/8Arkf5iqirySKiruw3+wrvH3ov++j/AIVRuLeS1lMUoww5612Vc1rn/IQ/4AP61rUpqKujScEldGbRRRWBiPjjeaRY0GWY4ArQGhXZHWIexY/4VX03/kJQf71dZW1KmpK7NYQUlqchdWU1myiYD5uhByDVetzxD/y7f8C/pWHUTioysiJKzsFFFFQSFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVq6B/x/v/ANcj/MVlVq6B/wAf7/8AXI/zFXT+JFw+JHRVzWuf8hD/AIAP610tc1rn/IQ/4AP610VvhNanwmbRRRXIc5b03/kJQf71dZXJ6b/yEoP96usrqofCzelsYniH/l2/4F/SsOtzxD/y7f8AAv6Vh1jV+NmdT4gq3Fpl5MMrAwHq3H862tL05LeJZZFBmYZ5/h9q0WZUUsxCgdSTirjRuryLjT0uzmDo16Bny1P0YVVmtprc/vYmT3I4rq1vLZjhbiIn03ipJUWWF0YAqw5zVOjF7Mfs10OLooqSCF7iZYoxlmNcxiMALEAAknoBVyPSr2QZEBA/2iBXQWVhDZIAoDSd3PU1YkkSJd0jqg9WOK6I0dPeNVS7nMto16BnygfowqpLBLA22WNkPuK6+O4hmOI5kc+isDSyxRzRlJEDKeoNN0U9mN0l0OLoq7qVgbKcbcmJ+VPp7VSrnaadmYtWdmTRWlxOu6KF2X1A4pJrae3AMsTID0JHFdLpH/ILh/H+Zp2oWhvIo4s4XzAWPtg1t7G8bo19npc5q3tJ7okQxlsdT0A/GppdKvIULtFlQMnaQcV08USQxrHGoVV6AUsn+qfPoapUFbUfslbU4qiiiuYwCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACtXQP+P9/wDrkf5isqtXQP8Aj/f/AK5H+Yq6fxIuHxI6Kua1z/kIf8AH9a6Wua1z/kIf8AH9a6K3wmtT4TNooorkOct6b/yEoP8AerrK5PTf+QlB/vV1ldVD4Wb0tjE8Q/8ALt/wL+lY0IBnjDdCwz+dbPiH/l2/4F/SsPpWNX42RP4jt6xtfWUxxFQTECd2PXtmr2n3qXluGyPMAw6+9WyAQQRkHsa6WlOOhs1zI4irEN7cW6FI5WCkYx1Fb9xo1rPkqpib1Tp+VYt5pk9n8xw8f99f6+lc0qcoamLhKOpSrd0C3ASS4I5J2r9O9YVdVpK7dMh98n9TToq8gpr3i4zBVLHoBk1yF3dSXc7SOTj+EegrrpEEsbRtnDAg496z/wCw7P8A6af99VtVjKWiNJxctjm1ZkYMpIYcgjtXW2FwbqyjlP3iMN9RVb+w7P8A6af99VctraO1hEUedoOeTSpwlF6ihFxepX1aETadJxynzD8P/rZrlq7G75sp8/8APNv5Vx1RXWpNXc6rSP8AkFw/j/M1dqlpH/ILh/H+Zqe6YpZzspwwjYg+nFbx+FGsfhRmajrDRSGG2IyvDP159BVAaxeeWyM6sGGMleR+VUKK5HUk3e5g5tsKKKKggKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK09CYLqBH95CP5H+lZlTWk/2a6jm7Kefp3qou0kyouzudjXP6/ERcxy44ZMfiD/APXrfVg6hlOVIyCO9Q3drHeQGKTjuCOxrrnHmjY6JK6scfRV+bR7uJjtTzF7FT/Smx6VeyNjySo9WOK5OSW1jn5X2HaPEZNSjI6JljXUVT0+wSxiIzukb7zf0q4TgZNdVOPLHU3hGyMHxA4MsCdwpP5//qrGq1qNyLq9eQH5B8q/QVXjQySpGOrEAfjXNN80mzCTvIWOV4XDxuVYdwa1rbXnXC3Ee8f3l4P5VXudGuYOUHmp6qOfyrPIKnBBBHY0XlBjvKJ2Ftdw3aboXBx1HcVKyhlKsAQRgg9657Q4ZTd+cARGFIJ7H2roq6oSco3ZvF3V2chfW4tbySIfdByv0NdFpLbtMh9gR+prE1lw2pSY/hAH6VoaDOGgkgJ+ZTuH0P8An9axp2VRozhpNo1J3aO3kdACyqSAfXFYP9v3X/POH8j/AI10RGRg9K5i+0ua2lYxozxE5BAzj61dXmWqKqcy1RL/AG/df884fyP+NH9v3X/POH8j/jWXtOcYOfSp4rK5mP7uBz7kYH51ipzezMuaRYuNYubiFoiI1VuDtByR+dZ9XLvTZ7OFZJSmGOMA9DVOplzX94Ur31Oq0j/kFw/j/M1Nef8AHjcf9c2/lUOkf8guH8f5mprz/jxuP+ubfyrrj8HyOhfCcfRRRXEcoUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAGrpmq/ZgIZ8mLs3df/rVvxyxzJvjdXX1Bri6ckjxtuR2U+qnFawquOjNI1GtGdrRXJrqd6o4uH/HmhtTvWHNw34YFa+3iX7VHVSSJEheR1VR3JxWDqWr+cpgt8hDwz+v09qynkeVt0js59WOabWc6zeiJlUb0QVJA4iuI5D0Vg35Go6KxMztIpo5kDxOGU9wacVVuqg/UVxaSPE26N2Q+qnFWV1S9UYFw34gGulV11Rsqq6nWVRvtSis0IBDTdlHb61z8l/dyjDXD49AcfyqtSlX7CdXsOd2kdnY5Zjkmn29w9rOssZ+YdvUelRUVz36mR1lnqEF4o2MFfuhPP/16t1xHSrKX93GMLcSY9Cc/zrojX7o1VXuddRXKHVb0jH2hvyFQSXVxNxJNIw9CxxTdddh+1Rsa7cxPCkKOrOH3EA5xwf8AGsKiisJy5ncylLmdzqdI/wCQXD+P8zU97/x43H/XNv5VySTSxf6uV0/3WIpXuJpBiSaRh6MxNaqslG1jRVNLEdFFFYGIUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB/9k=");
                        db.collection(DatabaseConstants.imgColName).document(imgUserId).set(dataImgUser);
                    }
                }
            }
        });

        try {
            Thread.sleep(6000L);    // give 5 second between tests to be safe
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }


    /**
     * make sure for sure that everything was removed
     */
    @After
    public void tearDown() {
        if (testEventId != null) {
            db.collection(DatabaseConstants.eventColName).document(testEventId).delete();
            db.collection(DatabaseConstants.imgColName).document(testImgId).delete();
            testEventId = null;
            testImgId = null;
        }
        if (testUserId != null) {
            db.collection(DatabaseConstants.usersColName).document(testUserId).delete();
            db.collection(DatabaseConstants.imgColName).document(imgUserId).delete();
            testUserId = null;
            imgUserId = null;
        }
        if (imgUserId != null) {
            db.collection(DatabaseConstants.imgColName).document(imgUserId).delete();
            imgUserId = null;
        }
    }


    /**
     * test delete event functionality
     * @throws UiObjectNotFoundException
     */
    @Test
    public void deleteEvent() throws UiObjectNotFoundException {
        //go to the event list
        onView(withId(R.id.nav_ad_events_btn)).perform(click());

        //wait to get everything loaded
        try {
            Thread.sleep(5000L);    // give 5 second between tests to be safe
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        //use this to scroll as animations are causing errors
        UiDevice device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
        UiScrollable scroll = new UiScrollable(new UiSelector().scrollable(true).className("android.widget.ScrollView"));
        scroll.setAsVerticalList();

        UiSelector selector = new UiSelector().text(testEventName);
        scroll.scrollIntoView(selector);
        UiObject eventToClick = device.findObject(selector);

        if (eventToClick.exists()) {
            eventToClick.click();

            try {
                Thread.sleep(5000L);    // give 5 second between tests to be safe
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            //click the delete button
            onView(withId(R.id.delete_btn)).perform(click());

            try {
                Thread.sleep(7000L);    // give 5 second between tests to be safe
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
//
            final boolean[] eventDeleted = {false};
//
            // verify that it was actually deleted from db
            db.collection(DatabaseConstants.eventColName).document(testEventId).get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
                @Override
                public void onComplete(@NonNull Task<DocumentSnapshot> task) {
                    DocumentSnapshot documentSnapshot = task.getResult();
                    if(!documentSnapshot.exists()){
                        eventDeleted[0] = true;
                        testEventId = null;
                    }
                }
            });

            try {
                Thread.sleep(5000L);    // give 5 second between tests to be safe
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            assertEquals(eventDeleted[0], true);

            try {
                Thread.sleep(5000L);    // give 5 second between tests to be safe
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }

    }

    /**
     * test delete user functionality
     */
    @Test
    public void deleteUser() throws UiObjectNotFoundException {

        onView(withId(R.id.nav_ad_users_btn)).perform(click());

        //wait to get everything loaded
        try {
            Thread.sleep(5000L);    // give 5 second between tests to be safe
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        //use this to scroll as animations are causing errors
        UiDevice device = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
        UiScrollable scroll = new UiScrollable(new UiSelector().scrollable(true).className("android.widget.ScrollView"));
        scroll.setAsVerticalList();

        UiSelector selector = new UiSelector().text(testUserName);
        scroll.scrollIntoView(selector);
        UiObject eventToClick = device.findObject(selector);

        if (eventToClick.exists()) {
            eventToClick.click();
//
            //click the delete button
            onView(withId(R.id.delete_btn)).perform(click());

            try {
                Thread.sleep(5000L);    // give 5 second between tests to be safe
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            final boolean[] userDeleted = {false};

            // verify that it was actually deleted from db
            db.collection(DatabaseConstants.usersColName).document(testUserId).get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
                @Override
                public void onComplete(@NonNull Task<DocumentSnapshot> task) {
                    DocumentSnapshot documentSnapshot = task.getResult();
                    if(!documentSnapshot.exists()){
                        userDeleted[0] = true;
                        testUserId = null;
                    }
                }
            });

            try {
                Thread.sleep(5000L);    // give 5 second between tests to be safe
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            assertEquals(userDeleted[0], true);
        }

    }


}